---
output-file: dolthub.html
---

# DoltHub {#sec-dolthub}

[DoltHub](https://www.dolthub.com) is a place to share Dolt databases. We host public data for free! DoltHub adds a modern, secure, always on database management web GUI to the Dolt ecosystem. Edit your database on the web, have another person review it via a pull request, and have the production database pull it to deploy.

## What is DoltHub {#sec-what-is-dolthub}

DoltHub is GitHub for Dolt. DoltHub acts as a [Dolt remote](https://docs.dolthub.com/concepts/dolt/git/remotes) you can [clone](https://docs.dolthub.com/cli-reference/cli#dolt-clone), [push](https://docs.dolthub.com/cli-reference/cli#dolt-push), [pull](https://docs.dolthub.com/cli-reference/cli#dolt-pull) and [fetch](https://docs.dolthub.com/cli-reference/cli#dolt-fetch) from. DoltHub adds [permissions](https://docs.dolthub.com/concepts/dolthub/permissions), [pull requests](https://docs.dolthub.com/concepts/dolthub/prs), [issues](https://docs.dolthub.com/concepts/dolthub/issues), and [forks](https://docs.dolthub.com/concepts/dolthub/forks) to the Dolt ecosystem. Additionally, DoltHub has a modern SQL workbench built in so you can explore and change databases on the web.

## Getting Started {#sec-dolthub-getting-started}

DoltHub has many uses. We recommend getting started by [sharing a database](https://docs.dolthub.com/products/dolthub/data-sharing).

This documentation will walk you through discovering data on DoltHub, cloning a copy locally, making a change on a fork, and submitting a pull request to the original database.

## DoltHub API {#sec-dolthub-api}

DoltHub has an [API](https://docs.dolthub.com/products/dolthub/api) you can script against. The documentation covers:

1. [Authentication](https://docs.dolthub.com/products/dolthub/api/authentication)

2. [SQL API](https://docs.dolthub.com/products/dolthub/api/sql) - Used to make read or write SQL queries to a DoltHub database

3. [CSV API](https://docs.dolthub.com/products/dolthub/api/csv) - Used to download CSV format files of DoltHub tables

4. [Database API](https://docs.dolthub.com/products/dolthub/api/database) - Used to interact with DoltHub databases and pull requests

5. [Hooks](https://docs.dolthub.com/products/dolthub/api/hooks) - Used to receive change events to your DoltHub databases
