---
output-file: dolt-install.html
---

# Installing Dolt {#sec-install-dolt}

Dolt is extremely simple to install. Dolt is a single ~100 megabyte program. To install it, you download or compile that program and put it on your PATH. To install in specific operating systems, follow the instructions below:

::: {.panel-tabset}

## Windows {#sec-install-dolt-windows}

### winget {#sec-install-dolt-windows-winget .unnumbered}

```bash
winget install dolt
```

<br/>

### Chocolatey {#sec-install-dolt-windows-chocolatey .unnumbered}

```bash
choco install dolt
```

Both `.msi` files and `.zip` files are available.

<br/>

### Scoop {#sec-install-dolt-windows-scoop .unnumbered}

```bash
scoop install dolt
```

<br/>

### MSI Files {#sec-install-dolt-windows-msi .unnumbered}

The easiest way to install Dolt on Windows is to use the MSI files that are provided with each release. They can be found in the Assets section of every release. Grab the latest [here](https://github.com/dolthub/dolt/releases/latest).

<br/>

### `.zip` Archive {#sec-install-dolt-windows-zip .unnumbered}

For those preferring to install Dolt manually a zipped archive is provided with the requisite executables. It can be found in assets along with the [latest release](https://github.com/dolthub/dolt/releases/latest).

## macOS {#sec-install-dolt-mac}

### Install Script {#sec-install-dolt-macos-install-script .unnumbered}

The download script for Linux can be used, as OSX is a `*nix` system. It will download the appropriate binary, and place it in `/usr/local/bin`:

```bash
sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'
```

<br/>

### Homebrew {#sec-install-dolt-macos-homebrew .unnumbered}

A Homebrew formula is available with with every release, so Mac users using Homebrew for package management can build Dolt from source with a single command:

```bash
$ brew install dolt
==> Downloading https://homebrew.bintray.com/bottles/dolt-0.18.3.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/c03cc532d5045fa090cb4e0f141883685de3765bf1d221e400c750b3ae89e328?response-content-disposition=attachment%3Bfilename%3D%22dolt-0.18.3.catalina.bottle.tar.gz%22&Policy=eyJTdGF0
######################################################################## 100.0%
==> Pouring dolt-0.18.3.catalina.bottle.tar.gz
ðŸº  /usr/local/Cellar/dolt/0.18.3: 7 files, 56.9MB
```

Which will install Dolt as follows:

```bash
$ ls -ltr $(which dolt)
lrwxr-xr-x  1 oscarbatori  admin  30 Aug 26 16:49 /usr/local/bin/dolt -> ../Cellar/dolt/0.18.3/bin/dolt
```

<br/>

### MacPorts {#sec-install-dolt-macos-macport .unnumbered}

On macOS, Dolt can also be installed via a [community-managed port](https://ports.macports.org/port/dolt/) via [MacPorts](https://www.macports.org/):

```bash
sudo port install dolt
```

## Linux {#sec-install-dolt-linux}

For Linux users, an installation script is available that will detect your architecture, download the appropriate binary, and place in `/usr/local/bin`:

```bash
sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'
```

The use of `sudo` is required to ensure the binary lands in your path.

:::
