project:
  type: book
  output-dir: docs

book:
  title: Africa CDC Database
  subtitle: Technical Handbook
  author:
    - name: Dr Jonathan Epstein
      orcid: 0000-0002-1373-9301
      email: epstein@ecohealthalliance.org
      affiliation: 
        - name: EcoHealth Alliance
          city: New York
    - name: Ava Sullivan
      orcid: 0000-0003-4339-2430
      email: sullivan@ecohealthalliance.org
      affiliation:
        - name: EcoHealth Alliance
          city: New York
    - name: Shannon Ball
      orcid: 0000-0001-8306-3493
      email: ball@ecohealthalliance.org
      affiliation:
        - name: EcoHealth Alliance
          city: New York
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - part: Database
      chapters:
        - 01-database.qmd
        - 02-database-schema.qmd
    - part: Tools
      chapters:
        - 03-dolt-install.qmd
        - 04-dolthub.qmd
        - 05-rstats.qmd
    - part: Data Sources
      chapters:
        - 06-pact.qmd
        - 07-pact-fetch.qmd
        - 08-acdc-db-search.qmd
        - 09-pact-update.qmd
    - part: Appendix
      chapters:
        - 10-alternate-sources.qmd
        - 11-update-alternate-sources.qmd
    - part: Exporting the Database
      chapters:
        - 12-data-export.qmd
  cover-image: images/acdc_eha.png
  search: true
  repo-url: https://github.com/ecohealthalliance/acdc-db-handbook/
  repo-actions: [edit]
  downloads: [pdf, epub]

bibliography: book.bib

format:
  html:
    theme: lumen
    highlight-style: breeze
  pdf:
    documentclass: scrreprt
    highlight-style: breeze
  epub:
    cover-image: images/acdc_eha.png
    highlight-style: breeze
