```{r setup, include = FALSE}
library(quarto)
library(dplyr)
library(here)
library(airtabler)
library(kableExtra)
library(rmarkdown)

for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

airtable_metadata <- airtable(
  base = "appAL7fJUpBPYtOq4", 
  tables = "Meta Data"
)$`Meta Data`$select()
```

# Introduction {#sec-introduction}

This handbook provides instructions for developing and maintaining the Research Information Gateway (RIG) - a resource that catalogs African infectious disease research to support continental public health initiatives on zoonotic pathogens.

## About the database {#sec-about-database}

EcoHealth Alliance is leading the development of a comprehensive database cataloging active infectious disease research initiatives and scientists across Africa. This resource centralizes information about scientific research on the continent specifically relevant to understanding, detecting, and responding to zoonotic pathogens.

Following integration with the Africa CDC Knowledge hub, this database will provide a detailed, searchable, and visual platform (accessible via a dashboard) containing data on major (multi-year) and active One Health research projects. It includes critical information such as:

- Research subject matter and focus areas
- Project duration
- Geographical locations and research sites
- Key personnel and investigators
- Links to publicly available reports, preprints, and publications

A particularly valuable feature is the directory of subject matter experts associated with research initiatives across the continent. This roster can be utilized by public health practitioners seeking expert consultations to support training activities, surveillance programs, or outbreak response efforts.
